### ISSUE TITLE
on-click attribute for map markers

### ISSUE THREAD

**Issue by positlabs** [GoogleWebComponents/google-map#100]
For convenience-sake, there should be an on-click attribute on the map marker components.

```
<google-map-marker on-click="{{onClickMarker}}" latitude="37.779" longitude="-122.3892" title="Go Giants!"></google-map-marker>
```

**Comment by ebidel** [comment]
I don't think the issue title matches what the PR is doing, but I'm not sure we want to add all these listeners to every instance of a marker element. Most people will never listen to them so it's wasteful.

It's fairly easy to add manually:

    google.maps.event.addListener(googleMarkerEl.marker, 'click', function(e) { })

**Comment by positlabs** [comment]
What if we add the event listeners when the attribute is changed (e.g. `"on-clickChanged": function(){add listener}`) as opposed to adding them all during initialization?

**Comment by ebidel** [comment]
Polymer treats `on-*` attributes special for the declarative event handlers. Perhaps this is a opt-in boolean attribute someone can use on the element? `<google-map-marker events>` would mean setup the listeners on init.

**Comment by positlabs** [comment]
Ohh yes I like that approach. @DracoNoir, do you want to add this as part of your PR?

**Comment by DracoNoir** [comment]
Yes, although I'm going to go a step farther and separate it into two sets of events:  clickEvents and mouseEvents.  This will allow a developer to have finer-grained control over which listeners are registered (I suspect that the former will be used more than the latter).

**Comment by ebidel** [comment]
Should be fixed in https://github.com/GoogleWebComponents/google-map/pull/102/files
