### ISSUE TITLE
Can markers be in their own polymer-element?

### ISSUE THREAD

**Issue by ryantheleach** [GoogleWebComponents/google-map#106]
Is it possible to do the following?

    <polymer-element name="markers-list" attributes="markers map">
      <style>
      </style>
      <template>

    <template repeat="{{marker in markers}}">
            <google-map-marker latitude="{{marker.latitude}}" longitude="{{marker.longitude}}" title="     {{marker.name}}"></google-map-marker>
    </template>

I've been trying but I can't work it out. I suspect it's due to the markers not appearing in the correct content container.

**Comment by ebidel** [comment]
`<google-map-marker>` only makes sense as a child of `<google-map>` (e.g. they need a map to render on. What are you trying to do?

**Comment by ryantheleach** [comment]
I had a seperate element for the map markers so that I could databind them to a datasource.

I nested the custom element inside the google map element. I've since worked around this by making a custom google map element, that takes a databinding which it then maps to a repeating template of markers.

**Comment by ryantheleach** [comment]
Learning more about Polymer I suspect it's due to the google-markers appearing in the shadow dom of a child element, theres probably no easy fix for this.
