### ISSUE TITLE
Deprecate showCenterMarker

### ISSUE THREAD

**Issue by ebidel** [GoogleWebComponents/google-map#109]
We've had proper marker support for a while. The `showCenterMarker` is convenient but adds to the complexity of the element and [causes issues with `fitToMarkers`](https://github.com/GoogleWebComponents/google-map/issues/69#issuecomment-76664722). We should deprecate this feature. Users should create markers the recommended way, via `<google-map-marker>`

**Comment by atotic** [comment]
showCenterMarker is gone
