### ISSUE TITLE
google-map-search: no result not tackled

### ISSUE THREAD

**Issue by supita** [GoogleWebComponents/google-map#111]
If I submit a query that gives no results, I'll get an error. This could be avoided if in the function `gotResults` the response status is checked (`status == google.maps.places.PlacesServiceStatus.OK`) or if it's checked that there's any element in the array of results.

**Comment by ebidel** [comment]
Closing as this is pre Polymer 1.0. Please reopen if you can still reproduce or want to see this implemented in the new element.
