### ISSUE TITLE
Null pointer for marker

### ISSUE THREAD

**Issue by Neill83** [GoogleWebComponents/google-map#114]
Hi!

Using google-map.html with GWT Super-Dev-Mode I got a Nullpointer:

Uncaught TypeError: Cannot read property 'setMap' of null
  Polymer.detached	
  base.detachedCallback	
  $removeChild_0_g$	
  orphan_0_g$	
  detach_0_g$	
  build_f_HTMLPanel1_0_g$	
  get_f_HTMLPanel1_0_g$	
  createAndBindUi_0_g$	
  createAndBindUi_1_g$	
  MyView_1_g$	
  onModuleLoad_3_g$	
  init_2_g$	
  initializeModules_0_g$	
  apply_0_g$	
  entry0_0_g$	
  (anonymous function)	
  gwtOnLoad_0_g$	
  (anonymous function)	

Your detached: function() (on line 196) needs a null check I think.

Regards.

**Comment by ebidel** [comment]
Fixed in https://github.com/GoogleWebComponents/google-map/pull/113
