### ISSUE TITLE
[Polymer 1.0] attributeChanged not available for native attributes

### ISSUE THREAD

**Issue by atotic** [GoogleWebComponents/google-map#126]
`attributeChanged()` is not available in Polymer 1.0. It is used to pass options to `<google-map>` and `<google-map-marker>`

Need to find a 1.0 pattern.

**Comment by ebidel** [comment]
Would the native CE lifecycle callback work. `attributeChangedCallback`?

**Comment by atotic** [comment]
I forgot that native custom element api does notify you of attribute changes.
