### ISSUE TITLE
Zooming the map in Firefox

### ISSUE THREAD

**Issue by MetalMatze** [GoogleWebComponents/google-map#130]
Hey,

I'm using this component in a project like this:

    <google-map latitude="52.520854" longitude="13.409515" z="12" fitToMarkers disableDefaultUI flex>
        <template repeat="{{ locations }}">
            <google-map-marker
                    latitude="{{ location.coordinates[0] }}"
                    longitude="{{ location.coordinates[1] }}"
                    title="{{ address }}">
                <div class="google-map-marker-content">
                    <p>{{ description }}</p>
                </div>
            </google-map-marker>
        </template>
    </google-map>
    
The locations are fetched with `<core-ajax>`. Everything is fine in Chrome.
But if I want to zoom in with Firefox, the map zooms in for 200ms, and then goes back to z=12...

![output](https://cloud.githubusercontent.com/assets/872251/7733780/c46d0084-ff31-11e4-9f44-3ee0dbac34b0.gif)

**Comment by ebidel** [comment]
Closing as this is pre Polymer 1.0. Please reopen if you can still reproduce with the new element.
