### ISSUE TITLE
Need to cut 1.0 release

### ISSUE THREAD

**Issue by mbleigh** [GoogleWebComponents/google-map#131]
Wasn't tagged, so bower is throwing errors when trying to install `google-web-components` (which depends on a 1.0.0 tag)

**Comment by ebidel** [comment]
Yep. I need to tag all the components. I'm waiting on google-drive and google-signing to get the 0.8 branches merged. Then polymer to tag 1.0. I want to not update bower.jsons and tag twice.

**Comment by ebidel** [comment]
cc @addyosmani
