### ISSUE TITLE
Updating a map's coordinates no longer pans it to that location

### ISSUE THREAD

**Issue by jsilland** [GoogleWebComponents/google-map#133]
I upgraded to the 1.0 version yesterday and it appears that this is a recently introduced regression. In my element hosting the map, I used to be able to set the `latitude` and `longitude` of the map element and the map would automatically center itself on the new coordinates, but it appears to no longer be the case. In the inspector, `latitude` and `longitude` no longer show as attributes on `google-map` element either.

Looking at the code, it seems to me like these properties are missing an `observer`:

```
latitude: {
        type: Number,
        value: 37.77493,
        notify: true,
        reflectToAtrribute: true
      }
```

The workaround is to access the underlying `map` property and essentially replicate the code in the `_updateCenter` method, i.e. manually center and pan the map.

**Comment by clintonjrobinson** [comment]
@jsilland I think it is a typo here https://github.com/GoogleWebComponents/google-map/blob/master/google-map.html#L328  adding a comma into updateCenter resolves this issue

    observers: [
      '_updateCenter(latitude,longitude)'
    ],

**Comment by ebidel** [comment]
Looks like a 0.9 leftover. Want to submit a PR?

**Comment by jsilland** [comment]
@ebidel will do, this afternoon.

**Comment by atotic** [comment]
FIxed.
