### ISSUE TITLE
Boolean value not updating (zoomable)

### ISSUE THREAD

**Issue by kretzm** [GoogleWebComponents/google-map#134]
I'm trying to set zoomable attribute to false, but the result is that is always true. Doing a deeper dive shows that the boolean value that we are assigning to the attribute is not captured, and always is assigned to true. 
`<google-map min-zoom="14" max-zoom="15" zoomable="false"></google-map>`

In the google-map.html file, if I use 
`scrollwheel: this.getAttribute('zoomable'),`
instead of
`scrollwheel: this.zoomable,`
under the `_getMapOptions` function, it works as expected.

Not sure if I'm setting the 'false' value for the zoomable attribute incorrectly. The zoomable value is set to 'true' by default in the properties, but it's unclear how then to actually set this to false.

**Comment by atotic** [comment]
Oops, fixed by renaming zoomale to disableZoom
