### ISSUE TITLE
click and mouse events problem

### ISSUE THREAD

**Issue by MeloJR** [GoogleWebComponents/google-map#143]
I was trying to register a handler on the `google-map-click` event but it seems that the `google-map` component never fires this event.

I inspected the code and it seems that there is a mistake in the `if` condition (lines 466-478):
```
_clickEventsChanged: function() {
      if (this.map && this.marker) {
          ...
      }
}
```
I searched for the `this.marker`variable and it never appears. If I remove `&& this.marker`it works perfectly. Have I done something wrong? Thank you.

P.S. There is the same problem with the `_mouseEventsChanged` method.

**Comment by atotic** [comment]
Good catch. Looks like a mistake introduced when I ported to 1.0
