### ISSUE TITLE
google-map-marker and google-map communication

### ISSUE THREAD

**Issue by atotic** [GoogleWebComponents/google-map#148]
MutationObserver is not the right solution, very heavyweight.

We should have event-based communication between markers and google-map. Might wait for children completion events to be implmeneted, that'd make it simpler.

**Comment by atotic** [comment]
Current solution uses MutationObservers, and it feels very heavyweight. There are lots of unnecessary callbacks when map is being scrolled. I’ve tried to solve similar problem before with events. Attach/detach would broadcast to parent. I am not sure if solution is general enough to deal with all edge cases (what happens if `map-marker` is attached to a div, before div gets attached to `google-map`.

https://github.com/Polymer/polymer/issues/1773 is a more general solution we're working on, which will help in all cases where you want to use light children as part of the element's API.

Lets wait for 1773 resolution.

**Comment by ebidel** [comment]
"heavyweight" because subtree modifications are happening on map scroll? We could remove `subtree: true` from the MO and just observer `childList` changes. I can't recall why `subtree: true` there.

**Comment by atotic** [comment]
scroll, zoom all cause avalanche of notifications. I was thinking of removing subtree, but what happens if someone puts their markers inside divs for fun?

**Comment by ebidel** [comment]
`<google-map-marker>` is the only supported child of `<google-map>`: https://github.com/GoogleWebComponents/google-map/blob/master/google-map.html#L79

**Comment by atotic** [comment]
Removing the subtree really cuts down on the number of calls: from 40 to 2 to show my demo map.

If we are already in that code: why is MutationObserver being recreated after every observation?

**Comment by ebidel** [comment]
I think that was partially your port? https://github.com/GoogleWebComponents/google-map/blob/0.4.2/google-map.html#L767 used to use polymer's `onMutation` API to listen once (then re-add). I think originally concern was that you may never see updates to marker children...to there was no need to have a persistent MO setup at load time.

Maybe that's a premature optimization. We could create a MO on load and destroy it on detach. WDYT?

**Comment by atotic** [comment]
I like it. Should I patch, or you?
remove recreation of MutationObservers.
stop watching subtrees.

**Comment by ebidel** [comment]
You're good at patching...I'm good at reviewing!

**Comment by atotic** [comment]
Will do right after you pull #165

**Comment by atotic** [comment]
Fixed for now. Not watching subtrees reduces callbacks substantially.
