### ISSUE TITLE
Blank maps in iron-pages

### ISSUE THREAD

**Issue by atotic** [GoogleWebComponents/google-map#151]
When embedding maps inside iron-pages, maps sometimes come up blank when page is show.

The fix is for every page to implement the following:

    behaviors: [ Polymer.IronResizableBehavior],
    listeners: { 'iron-resize': 'onResize' },
    onResize: function() {
      if (this.$.map)
        this.$.map.resize();
    }

I believe that google-map element itself should implement Polymer.IronResizableBehavior.
I'd like another set of eyes on this. @ebidel

**Comment by ebidel** [comment]
Yea, this has always been a source of pain and leftover in core-animate-pages days. I agree the element should do this for users.
