### ISSUE TITLE
Map don't update when Lat/Long properties are changed.

### ISSUE THREAD

**Issue by andrebq** [GoogleWebComponents/google-map#161]
The map component don't update the rendering when the user changes either the latitude or logitude properties.

Consider this example:

	<dom-module id="my-el">
	  <template>
		<google-map id="map" latitude="{{loc.latitude}}" longitude="{{loc.longitude}}">
		</google-map>
		<button on-click="changeloc">Change location</button> 
		
		<script>
		  Polymer({
		    is: 'my-el',
		    properties: {
		    	loc: Object
		    },
		    changeloc: function(ev) {
		    	this.loc = {
		    		latitude: -19,
		    		longitude: -43,
		    	};
		    	/* it's expected that the map will be centered at -19,-43 now
		    	  but instead the map doesn't change and the setTimeout is required.
		    	*/
		    	/* this timeout only works to force the map to be updated. */
		    	setTimeout(function(){
		    	  this.$.map.resize();
		    	}.bind(this), 1000);
		    }
		  })
		</script>
	  </template>
	</dom-module>

**Comment by andrebq** [comment]
As a test, I include a test on attributeChanged to call _updateCenter when either latitude or longitude is changed. But this only works when calling map.setAttribute('latitude', value);

    attributeChanged: function(attrName, oldVal, newVal) {
      if (!this.map) {
        return;
      }
      // Cannot use *Changed watchers for native properties.
      switch (attrName) {
        case 'draggable':
          this.map.setOptions({draggable: this.draggable});
          break;
		case 'latitude':
		case 'longitude':
		  this._updateCenter();
		  break;
      }
    },

The "fix" doesn't work with map.latitude = ....

**Comment by jsilland** [comment]
This appears to be a dupe of https://github.com/GoogleWebComponents/google-map/issues/133, which is fixed in the master branch.

**Comment by andrebq** [comment]
Moving to master fixed the problem.
