### ISSUE TITLE
setTimeout causes map to be blank

### ISSUE THREAD

**Issue by derek1906** [GoogleWebComponents/google-map#166]
Adding a map after a period of time upon page load seems to result in a blank map. Here is a [demo](https://github.com/derek1906/google-map-demo/tree/22de2564db3dfc891c46f0e5387787f25d3f4c2b).

Screenshot:  
![sss](https://cloud.githubusercontent.com/assets/5441361/8170281/43de9e7a-1375-11e5-91ba-3e229c6d5f2a.png)

>The top one is a map created with `<google-map>` which is already in the HTML source. The bottom one on the other hand is created with `.createElement` wrapper in a `setTimeout` with a delay of 1 second.

**Comment by atotic** [comment]
We just fixed that one, should be in #master shortly.
