### ISSUE TITLE
javascript not loading in crosswalk/webview

### ISSUE THREAD

**Issue by isaldarriaga** [GoogleWebComponents/google-map#169]
i wrapped an angularJS SPA demo with the google-map web component inside.

The element works perfectly in the web browser, but not in a hybrid app in mobile device (android/amazon fireOS).

I remote debugged the device with chrome's inspector with the following result:

![image](https://cloud.githubusercontent.com/assets/6360185/8304069/9d5547ee-1968-11e5-938e-a920ed0f06df.png)

steps to repro:
install ionic framework (or just cordova)
$ionic create googlemapdemo blank
optionally add crosswalk support (this replace webview)
edit the index.html and add the google-map
connect the device (debugging enabled)
$ionic run android
goto chrome://inspect/#devices and see the network tab

**Comment by ebidel** [comment]
I can't be sure, but have you checked that your webview has permission to access external resources like this? I know at least on Android there are settings like this.

**Comment by isaldarriaga** [comment]
Looks like the right permissions are already set:

<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="1" android:versionName="0.0.1" package="com.q.phonebook" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <application android:hardwareAccelerated="true" android:icon="@drawable/icon" android:label="@string/app_name" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.Black.NoTitleBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
    <uses-sdk android:minSdkVersion="14" android:targetSdkVersion="21" />
</manifest>

The device show in the settings the permissions are applied.

**Comment by isaldarriaga** [comment]
The problem disappeared after re-creating the environment for the demo project with the CLI tools. So the isue is not related to the web component.
