### ISSUE TITLE
'google-map-click' event is not fired 

### ISSUE THREAD

**Issue by yingqiaogit** [GoogleWebComponents/google-map#175]
The scenario description has two parts as follows, including in the original problem, and the problem that occurs after a work around is used. 

Original: 
1) the map is defined as below in html: 

    <google-map clickEvents="true" mouseEvents="true" latitude="{{lat}}" longitude="{{lng}}" >
          <google-map-marker latitude="{{markerlat}}" longitude="{{markerlng}}"
                                                  draggable="true">
          </google-map-marker>
     </google-map>

2) The handler is configured as below in script file:

var gmap=document.querySelector('google-map');
gmap.addEventListener('google-map-click',function(event){
            var location;
            console.log(event);
            app.markerlat = event.latLng.lat();
            app.markerlng = event.latLng.lng();
            console.log(app.markerlat + "," + app.markerlng);
}); 

The handlers for mouse events (e.g. click, mouse, and drag) related to a map are configured in the _initGMap(). However, the properties such as clickEvents and mouseEvents are as false at that moment. And, the handlers of google-map-click events and google-map-mouse events are cleared. Therefore, the google-map-click event won't be fired later.  

I used a workaround to let the google-map-click fired, but, the event is not a google map MouseEvent. It is not possible to retrieve the <lat,lng> from the event. 

The workaround is as below: 
gmap.addEventListener('google-map-ready', function(){

           gmap.mouseEvents=true;

           gmap._mouseEventsChanged();

           gmap.clickEvents=true;

           gmap._clickEventsChanged();

       });

Best regards,
Ying

**Comment by yingqiaogit** [comment]
Found a workaround for this problem. The <lat,lng> stores at the event.detail.latLng

**Comment by yingqiaogit** [comment]
works with 

<google-map api-key="xxxxxxxxxxxxxxxxxxxx" click-events="true" mouse-events="true" latitude="{{lat}}" longitude="{{lng}}">
                                <google-map-marker id="markedLocation" latitude="{{markerlat}}" longitude="{{markerlng}}" draggable="true">
                                </google-map-marker>
                            </google-map>

**Comment by tigerhawkvok** [comment]
As an update to anyone else hunting down this issue, the event details are now in `event.originalEvent.details.latLng`, like so:

```coffee
    $("#myGooglemap").on "google-map-click", (e) ->
      # https://developers.google.com/maps/documentation/javascript/3.exp/reference#MouseEvent
      latLngOjb = e.originalEvent.detail.latLng
```
