### ISSUE TITLE
Dynamically create/add google-map-markers to google-map

### ISSUE THREAD

**Issue by parondeau** [GoogleWebComponents/google-map#177]
I'm looking to dynamically add map markers to a ```<google-map>``` element after the map has loaded. 
Since I'm looking to add up to *n* markers, I can't simply add ```<google-map-markers>``` to the markup at the start and edit the latitude and longitude attributes. 

I have tried this, with no luck:

```html
<google-map id="googleMap" disable-default-ui map="{{map}}" latitude="37.779" longitude="-122.3892">
</google-map>
```
```javascript
var marker = document.createElement('google-map-marker');
marker.latitude = lat;
marker.longitude = long;
document.getElementById('googleMap').appendChild(marker);
```

These markers appear correct in the DOM but do not show up on the map at all. 

Is there a workaround for this?

**Comment by ebidel** [comment]
This should definitely work and if it doesn't, it's a bug. Can you provide
a working jsbin of the issue?

**Comment by ebidel** [comment]
Ah, and make sure to use Polymer.appendChild since you're modifying the
light dom.

**Comment by parondeau** [comment]
Oh, you were right. Thanks so much.
