### ISSUE TITLE
Small error in the Documantation

### ISSUE THREAD

**Issue by KuhlDesign** [GoogleWebComponents/google-map#182]
Down in the api reference is said that "disableDefaultUi" can be used to disable the UI, but actually it's "disable-default-ui".

**Comment by kamronbatman** [comment]
Since properties are camelCase in Polymer, and snake-case in HTML, I don't see a problem with this personally.

**Comment by ebidel** [comment]
Yea, they look right to me. See https://www.polymer-project.org/1.0/docs/devguide/properties.html#property-name-mapping
