### ISSUE TITLE
`markers` should be a property?

### ISSUE THREAD

**Issue by jakemac53** [GoogleWebComponents/google-map#183]
Currently this is just getting added inside `created`, but it seems like it should be an actual property. Without that it won't show up in docs and other tools which use hydrolysis won't see it as a valid property.

If there is a reason for not making it a property, could we make a getter/setter with proper annotations so it can be discovered that way?

**Comment by ebidel** [comment]
Yes. It should be declared in `properties` and initialized there instead of the 0.5 way in `created`. It should also be `readOnly: true` since the list is derived from the child marker nodes. 

Do you want to send a PR?

**Comment by jakemac53** [comment]
Sure, I can put something together tomorrow
