### ISSUE TITLE
Google maps infoWindow automatically open on page load

### ISSUE THREAD

**Issue by kirashone** [GoogleWebComponents/google-map#187]
Hi guys,
what code should i add for the infoWindow to appear automatically without pressing it.
Thank you guys so much for your help.

})(jQuery);
(function($) {
    'use strict';
    // Google Map Customization
    if ($("#gmap2").length > 0)
    {
        (function() {

            var map;

            map = new GMaps({
                el: '#gmap2',
                lat: 1.289701,
                lng: 103.812879,
                scrollwheel: false,
                zoom: 18,
                zoomControl: true,
                panControl: true,
                streetViewControl: true,
                mapTypeControl: true,
                overviewMapControl: true,
                clickable: true
            });

            var image = '';
            map.addMarker({
                lat: 1.289701,
                lng: 103.812879,
                icon: image,
                animation: google.maps.Animation.DROP,
                verticalAlign: 'bottom',
                horizontalAlign: 'center',
                backgroundColor: '#d3cfcf',
				title: 'Lima',
				infoWindow: {content: '<p>Address: No. 2 Kung Chong Road Singapore 159140</p>'
                }
            });

**Comment by ebidel** [comment]
Is this element code or pure maps api code? 

Anyways, according the maps api docs, info windows have an open method you can call to programmatically open them.

https://developers.google.com/maps/documentation/javascript/infowindows#open

**Comment by kirashone** [comment]
http://stages.a-wan.com/hybridmotors/
Hi ebidel, can you have a look at my website right to the bottom that's my map. When i click in the red marker it will display the infoWindow, but i want it to stay there by default. What code should i add? Can you please guide me along from my code what to add in as i'm abit noob here. Thank you

**Comment by ebidel** [comment]
When I click the red marker on https://elements.polymer-project.org/elements/google-map?view=demo:demo/index.html, the window stays open by default. If you want something different
than that,  I'd consult the Maps API documentation.
