### ISSUE TITLE
How to set Google map Side by Side

### ISSUE THREAD

**Issue by kirashone** [GoogleWebComponents/google-map#189]
i really need your guys help, please visit my website and scroll to the bottom at the map sector, my map cant align to side by side. Please help what code is needed to add in to align it to side by side.
http://stages.a-wan.com/hybridmotors

<?php
    if($contactmap == 'no'):
?>

<div class="clearfix col-sm-6"></div><div id="gmap" style="height: 440px;"></div>

<div class="clearfix col-sm-6"></div><div id="gmap2" style="height: 440px;"></div>

<?php endif; ?>

**Comment by atotic** [comment]
The issues here are for bugs in maps, not for help debugging your own site. Try stackoverflow, or Polymer google group.
