### ISSUE TITLE
Map.resize() with fit-to-markers

### ISSUE THREAD

**Issue by nickell** [GoogleWebComponents/google-map#192]
Without `fit-to-markers`, calling map.resize() works just fine. When that attribute is added, calling map.resize() sets the latitude to 0 and longitude to -180.

To replicate this issue, clone the [Polymer Starter Kit](https://github.com/PolymerElements/polymer-starter-kit), install the latest google-map and paste the following into any of the paper-material elements:

`<google-map latitude="38.907288" longitude="-77.036539" fit-to-markers></google-map>`

Am I doing anything wrong here? Let me know if I can provide any more information or help debug. And by the way, thanks for this awesome component, we are very excited about Polymer!

**Comment by nickell** [comment]
I probably should have done this before filing an issue. But reading the code makes it obvious that if there are no markers then it will center to the default google.maps.LatLngBounds() which unsurprisingly turns out to be 1 and -180.

Is there a reason why this line:
`var latLngBounds = new google.maps.LatLngBounds();`
isn't something like this?
`var latLngBounds = this.map.getBounds() || new google.maps.LatLngBounds();`

**Comment by ebidel** [comment]
Want to propose a PR?

**Comment by nickell** [comment]
Absolutely! I'll submit one shortly.

**Comment by TimvdLippe** [comment]
This issue was fixed in #196 but not correctly referenced to be auto-closed.

**Comment by nickell** [comment]
Thanks for the headsup @TimvdLippe
