### ISSUE TITLE
Demo not working on search

### ISSUE THREAD

**Issue by marcus7777** [GoogleWebComponents/google-map#193]
google-map-search [demo](https://github.com/GoogleWebComponents/google-map/blob/master/google-map-search.html#l13) is not working

I was trying the update it to P1 but no pins: [JSbin](http://jsbin.com/foyaro/edit?html,output)

    <!doctype html>
    <html>
     <head>
      <base href="http://polygit.org/components/">
      <script src="webcomponentsjs/webcomponents-lite.js"></script>
      <link rel="import" href="google-map/google-map.html">
      <link rel="import" href="google-map/google-map-search.html">
      <link rel="import" href="google-map/google-map-marker.html">
     </head>  
     <body>
      <template id="t" is="dom-bind">
        <style>
          google-map {
            height: 400px;
          }
        </style>
        <google-map-search map="{{map}}" query="Pizza"
                         results="{{results}}"></google-map-search>
        <google-map map="{{map}}" latitude="37.777"
                  longitude="-122.3777">
          <template is="dom-repeat" items="[[results]]">
            <google-map-marker latitude="{{item.latitude}}" longitude="{{item.longitude}}">
            </google-map-marker>
          </template>
        </google-map>
      </template>
       <script>
          document.getElementById('t').addEventListener('dom-change', function(e){ 
            document.querySelector('google-map-search').search();
          });
       </script>

     </body>
    </html>

**Comment by ebidel** [comment]
Believe this is related to https://github.com/GoogleWebComponents/google-map/pull/195/files

**Comment by vzhen** [comment]
Still not working

**Comment by ebidel** [comment]
We haven't done a release with those changes yet. Are you trying master?

**Comment by vzhen** [comment]
yes,  i copy the raw and replace directly. Still same error
`Uncaught TypeError: Cannot read property 'search' of null`

**Comment by ebidel** [comment]
Can you paste a jsbin of your code with the line number of that error.

**Comment by vzhen** [comment]
[jsbin](http://jsbin.com/tigazibori/edit?html,console,output)
I not sure it is marker problem or search. The markers are not show and it gives me search error.

**Comment by ebidel** [comment]
Ok, updated: https://github.com/GoogleWebComponents/google-map/pull/198

This should fix things this time :) Namely, the demo snippet was also incorrect.

**Comment by marcus7777** [comment]
Do I need an API key to get this to work

**Comment by ebidel** [comment]
Shouldn't, but it's recommended to use the Maps API with a key. I think it starts imposing rate limits.

**Comment by marcus7777** [comment]
![screenshot 2015-09-15 at 6 28 03 pm](https://cloud.githubusercontent.com/assets/6314260/9882928/8ebc9de8-5bd7-11e5-8787-ac2c8149ae93.png)
By the way I'm using master

**Comment by marcus7777** [comment]
add libraries="places" to fix

**Comment by marcus7777** [comment]
https://github.com/GoogleWebComponents/google-map/pull/206
