### ISSUE TITLE
Setting marker animation modes

### ISSUE THREAD

**Issue by WillDonohoe** [GoogleWebComponents/google-map#197]
Hi guys,

I'm looking to add a drop animation (google.maps.Animation.DROP) when a new pin is created using the google-map-marker element:

```
<google-map id="map" latitude="{{lat}}" longitude="{{lng}}" zoom="{{zoom}}">
  <template is="dom-repeat" items="{{points}}">
    <google-map-marker id="{{item.id}}" click-events latitude="{{item.lat}}" longitude="{{item.lng}}"></google-map-marker>
  </template>
</google-map>
```

I can't find a way to change the animation type without creating the marker programmatically using new google.maps.Marker().

```javascript
var marker = new google.maps.Marker({
  map: this.$.map.map,
  position: {
    lat: lat,
    lng: lng
  },
  animation: google.maps.Animation.DROP
});
```

This solution adds a lot more complexity to my application though. 

What would be your recommended solution for adding animations to markers?

Many thanks

**Comment by ebidel** [comment]
Right now, I think you'd have to loop over the marker elements and set:

    markerEl.marker.setAnimation(google.maps.Animation.DROP);

If you want to propose a PR that adds an `animation` property, that might be a good addition.
