### ISSUE TITLE
cannot install through bower

### ISSUE THREAD

**Issue by davossboss** [GoogleWebComponents/google-map#200]
Bower fails to install when the main property has more than one type of file, this has three html files in the main field.

**Comment by ebidel** [comment]
What version of Bower are you using? I ran `bower install GoogleWebComponents/google-map` with the latest and there were no errors.

**Comment by davossboss** [comment]
I'm currently using version 1.5.2 of bower, installed with npm.

**Comment by davossboss** [comment]
From: http://bower.io/docs/creating-packages/#bowerjson
Main:
The entry-point files necessary to use your package. Only one file per filetype.

**Comment by davossboss** [comment]
And here's the error in the cmd prompt:

bower EINVALID      Failed to read C:\Users\Karl\AppData\Local\Temp\Karl-PC-Karl\bower\google-map-14272-AJusk4\bower.json

Additional error details:
The "main" field has to contain only 1 file per filetype; found multiple .html files: ["google-map.html","google-map-search.html","google-map-marker.html","google-map-directions.html"]

**Comment by ebidel** [comment]
Fair enough. We'll fix that. 

I'd still like to understand why I don't get this error and you do. Is there anything different in the way you're installing the element?

**Comment by atotic** [comment]
Many Polymer elements do not comply with "single main" guideline (iron-behavior, etc). We use multiple main entries in catalog to display docs for multiple files.
The bower error is puzzling, I use 1.5.2 without problems. Is there some kind of a strict bower mode where warnings become errors?

**Comment by ebidel** [comment]
Yikes. I didn't realize that's the way the catalog worked :\ I'll revert https://github.com/GoogleWebComponents/google-map/commit/c4dc24051f2d26a93e245688ea3ac50a9bf8175a

**Comment by davossboss** [comment]
I'm not sure. I'm definitely getting an EINVALID and the files aren't installed to the bower-components folder. I'm just calling bower install --save GoogleWebComponents/google-map in the directory of my project, nothing else.

Unless there's some setting I need to change in bower?

**Comment by atotic** [comment]
You are not alone: https://github.com/PolymerElements/iron-ajax/issues/100
That guy fixed it by reinstalling bower. Could be some install weirdness, where you think you are running 1.5.2, but your are not.
I grepd bower source, and I can't find that error message.

Looking at bower CHANGELOG, multiple mains are tolerated. 
https://github.com/bower/bower/blob/master/CHANGELOG.md
Could be a windows specific bug too.

Good luck.

**Comment by davossboss** [comment]
Thanks, I'll try some reinstalls and ect.

**Comment by davossboss** [comment]
Turns out I just had to do a reinstall of Node.js and npm, wasn't on the latest version, so bower was installing incorrectly. Thanks for your help!

**Comment by atotic** [comment]
:+1:
