### ISSUE TITLE
google-map-marker latitude, longitude not "notify: true"

### ISSUE THREAD

**Issue by ihab** [GoogleWebComponents/google-map#207]
The `latitude` and `longitude` properties of `google-map-marker` are not declared `notify: true`. Is this deliberate, for a reason?

My use case is that I have a `draggable` `google-map-marker` and I want my parent component to automatically receive updates when the user drags the marker around.

**Comment by ebidel** [comment]
That's a good use case to support this. Want to submit a PR?

**Comment by ihab** [comment]
Will do, thank you!

**Comment by eximius313** [comment]
I believe that this issue can be now closed?

**Comment by ihab** [comment]
Thank you! Yes!
