### ISSUE TITLE
google-map-marker does not clean up listeners on detach

### ISSUE THREAD

**Issue by DracoNoir** [GoogleWebComponents/google-map#212]

**Comment by ebidel** [comment]
Want to do a PR?

**Comment by kamronbatman** [comment]
I will be willing to do a PR if I had more details on this problem.

**Comment by ebidel** [comment]
When the element is removed from the DOM (https://github.com/GoogleWebComponents/google-map/blob/master/google-map-marker.html#L235), any listeners that were setup should be removed.

Probably just:
```
google.maps.event.clearInstanceListeners(this.marker);
this._listeners = {};
```
