### ISSUE TITLE
google-map-marker double-registers event listeners when map is set

### ISSUE THREAD

**Issue by DracoNoir** [GoogleWebComponents/google-map#213]
The _mapReady() method unnecessarily calls _clickEventsChanged() and _mouseEventsChanged().

**Comment by ebidel** [comment]
This is by design. It waits for the maps api to be ready before adding the listeners. When `_clickEventsChanged()` gets called the first time at bootup, `this.maps` won't be set yet and https://github.com/GoogleWebComponents/google-map/blob/master/google-map-marker.html#L263 won't get called.
