### ISSUE TITLE
Get map bounds

### ISSUE THREAD

**Issue by Bodhiz** [GoogleWebComponents/google-map#214]
Hi,

I've implemented a google-map component, and I'd like to get map bounds through a function I call on-google-map-dragend event in order to display only the markers in the map view port. Unfortunately I can't figure out how to get those maps bounds and I'm thinking it's not currently possible. Am I right ? Is there a workaround or is it something planned for a future release ?

Thank you in advance for your answers.

**Comment by ebidel** [comment]
The element contains a .map property you can access to make all the raw
maps API calls.

**Comment by Bodhiz** [comment]
:+1:  Arghh yes ! It was that I was desperately looking for. My fault, bad reading of the doc. 
Thank you !
