### ISSUE TITLE
google-map-direcctions - Uncaught TypeError: window.google.maps.Load is not a function

### ISSUE THREAD

**Issue by ArgenioBonsanto** [GoogleWebComponents/google-map#216]
I've been trying to use the google-map-directions element in my app. Here is the code:
```
<google-map map="{{map}}" latitude="37.779" 
  longitude="-122.3892" zoom="13" disable-default-ui>
</google-map>

<google-map-directions map="{{map}}" 
  start-address="San Francisco"
  end-address="Mountain View">
</google-map-directions>
```
I am getting this error in the console:

Uncaught TypeError: window.google.maps.Load is not a function

What can I do to solve this problem?

**Comment by ebidel** [comment]
Can you post a jsbin of your code?

**Comment by ArgenioBonsanto** [comment]
here is the code in jsbin:

http://jsbin.com/wujicaboja/edit?html,output

thx for your collaborations

**Comment by ebidel** [comment]
http://jsbin.com/zugofojazo/edit?html,output. 

The map elements aren' being imported so I can't run the demo. But you have `<template is="dom-bind">` on your topmost template which is throwing an error in the console.

**Comment by ArgenioBonsanto** [comment]
I dont know how import google-map in jsbin man, but if I remove <google-map-direcctions> of the code, I see the map, the problems is when i use google-map-direcctions.

at this moment, get the error Uncaught TypeError: window.google.maps.Load is not a function

**Comment by ebidel** [comment]
polygit.org can be used for live jsbins :)

http://jsbin.com/varififele/edit?html,output works for me. This is pulling the latest versions from master. Note `start-address` and `end-address`. Properties are "-" separated and lowercased when used as attributes.

What version of the element(s) are you using?

**Comment by ArgenioBonsanto** [comment]
Thanx you, the problems is my version of google-maps,
