### ISSUE TITLE
google-map not working correctly when using webcomponents.min.js

### ISSUE THREAD

**Issue by kungufli** [GoogleWebComponents/google-map#218]
Some click events seems broken on the map (you can't zoom, drag the map or click on markers) in Firefox, Safari and IE when using `google-map` with `webcomponents.min.js` (0.7.15). It works normally in Chrome and Edge, or if you use `webcomponents-lite.min.js`.

**Comment by ebidel** [comment]
Can you post a jsbin been that repos the issue?

**Comment by kungufli** [comment]
@ebidel thanks for looking at that, here is the jsbin https://jsbin.com/buweluwoye/edit?html,output 
Also I just found that the problem appear only if `google-map` have the attribute `signed-in=true`.

**Comment by ebidel** [comment]
Very interesting! Thanks for the jsbin. I see it in Safari with the full poyfill.

Definitely a bug, but it's out of the scope for this element to fix it. This is an issue with the wc polyfill. I suggest filing this over there (https://github.com/webcomponents/webcomponentsjs). There's clearly something going on with events being swallowed and the signin layer the maps creates.

In the meantime, is there a reason you can't use the light version?

**Comment by ebidel** [comment]
Leaving open until we have a pointer from the wcjs issue.

**Comment by kungufli** [comment]
Unfortunately I actually have to use the full version of webcomponents because of https://github.com/Polymer/vulcanize/issues/223

**Comment by ebidel** [comment]
Closing in favor of https://github.com/webcomponents/webcomponentsjs/issues/426
