### ISSUE TITLE
Issue when trying to get on drag event

### ISSUE THREAD

**Issue by zohon** [GoogleWebComponents/google-map#221]
I cannot manage to get the event "google-map-drag" with polymer

http://jsbin.com/zoyipidume/1/edit?html,console,output

i cannot get the on-tap event inside a marker too.

**Comment by ebidel** [comment]
Yea this is tricky. The marker's infowindow popup is actually different dom than your `<h2 on-tap="selectPlace">`, so the event is never seen. I'm not show how to really fix this.

For the drag event, you need to use the property as `drag-events` when using it as an attribute.

**Comment by zohon** [comment]
Thanks for the help i manage a simple click event and call my polymer element.
Im using polymer with firebase and have a lot of fun.
hope to show you my web app soon to have feedback :D
