### ISSUE TITLE
Property singleInfoWindow does not work

### ISSUE THREAD

**Issue by evelijn** [GoogleWebComponents/google-map#224]
I added this property to the google-maps tag, but windows will still open simultaneously.

**Comment by ebidel** [comment]
Code please! Remember if you're using it as an attribute, you need to use `single-info-window`

**Comment by evelijn** [comment]
I'm sorry for this, I guess I'm not used to the way things work around here. I used `<google-maps singleInfoWindow="true">`but it makes sense to use `single-info-window`. Sorry for the stupid question, kinda new to this.

**Comment by ebidel** [comment]
No worries. Check out
https://www.polymer-project.org/1.0/docs/devguide/properties.html#property-name-mapping

**Comment by evelijn** [comment]
Thank you, that's helpful!
