### ISSUE TITLE
Marker Cannot display on Map

### ISSUE THREAD

**Issue by arulananth** [GoogleWebComponents/google-map#229]
view-source:http://www.qcityguide.com/qcg/restaurant/?aroundyou=5&search=1

**Comment by ebidel** [comment]
Please file issues with a summary and description of the issue.

**Comment by arulananth** [comment]
Hi Ebidel,

Sometime is running,sometime is not ,I use Inspect element 

iron-selector is empty.I mean marker coming out of the iron-selector element.
