### ISSUE TITLE
How to do near by search instead of text search using google-map-search

### ISSUE THREAD

**Issue by cvenkatasuresh** [GoogleWebComponents/google-map#239]
Am trying to get near by places for a given set of place types by using google-map-search component with out specifying search query, but current implementation return results only if query text is not empty? Any suggestions?

`<google-map-search map="[[map]]" query="" types="bowling_alley casino movie_rental movie_theater">
</google-map-search>`

**Comment by ebidel** [comment]
There's not. Does this even work in the Maps API-prop? `types` are filtering of the query text.

**Comment by cvenkatasuresh** [comment]
@ebidel am looking for a component to perform this https://developers.google.com/maps/documentation/javascript/places#place_search_requests, any suggestions?

**Comment by ebidel** [comment]
We'd have to provide a new method that does the nearbySearch. File a feature request?
