### ISSUE TITLE
Polymer Google-maps issue

### ISSUE THREAD

**Issue by kenny0202** [GoogleWebComponents/google-map#243]
I am building a MEAN Stack application with a combination of Polymer on the frontend.

I have built a paper-tabs element that is linked up with ngRoute.

Loading the different views everything works fines.

When I added a google-maps elements to the map view the initial load is fine.

So this is the following steps I took to create the issue.

Go to localhost:3000 -> loads into the /home view -> click on "Maps" tab which loads /map view containing google-maps -> click to any other tab so it loads the corresponding view -> click back to map and it generates an error with a blank gray screen where the map is suppose to be loaded.

The errors that I am getting are:

Maximum call stack size exceeded

Cannot read property 'click' of undefined

This is the polymer code that I am using for testing.

    <div ng-controller="MapController">
        <h1>Map</h1>
        <google-map latitude="37.77493" longitude="-122.41942" fit-to-markers>
            <google-map-marker latitude="37.779" longitude="-122.3892"                   
            draggable="true" title="Go Giants!"></google-map-marker>
            <google-map-marker latitude="37.777" longitude="-122.38911"></google-map-marker>
        </google-map>
     </div>

**Comment by ebidel** [comment]
This issue tracker is not meant for debugging development setups. If you can post a jsbin that repo's the issue, we're happy to take a look.
