### ISSUE TITLE
Possibility to highlight particular marker

### ISSUE THREAD

**Issue by eximius313** [GoogleWebComponents/google-map#246]
I have a list of places and each place is represented on the map with a marker.
When user selects a place I want to center the map on this particular marker without removing other markers.
It would be also great to turn on ```BOUNCE``` animation for this marker

**Comment by ebidel** [comment]
You can do this with the marker click events, setting the map's lat/lng to the clicked marker. I believe the marker is returned in the event. https://elements.polymer-project.org/elements/google-map?active=google-map-marker#clickEvents
