### ISSUE TITLE
Marker and map is not updating position in Angular 2

### ISSUE THREAD

**Issue by fr3dm4n** [GoogleWebComponents/google-map#253]
I am very new to Polymer, so I apologize, if this is not a bug

I use Polymer in Angular2 and was not able so move the coordinates of the map *and* the marker.

To demonstrate this I built two plunkers.

This one imports all components global in the index.html
http://plnkr.co/edit/GVNTRbTvYMSdHjvABEPu?p=preview
but the Marker is not visible, while the map is moving.

The funny part: If I move `<link rel="import" href="https://cdn.rawgit.com/download/polymer-cdn/1.2.3.2/lib/google-map/google-map.html">` to the view of app.ts the marker is visible, but the map is frozen: 
http://plnkr.co/edit/8uxh2agjg78O5Apr7FYq?p=preview

Can U help me?

**Comment by ebidel** [comment]
Something is unusual about the way Angular is attaching the marker element. I suspect it has something to do with it not knowing about the `Polymer.dom()` api and therefore, the distributed marker child element is never picked up by `getDistributedNodes()`: https://github.com/GoogleWebComponents/google-map/blob/master/google-map.html#L470. Polymer has a `distributeContent()` method for forcing distribution. It would be worth seeing if calling `this. distributeContent(true);` right before that line fixes it.

innerHTML works just fine, so it must not be using that:
http://jsbin.com/fetoyu/edit?html,output

**Comment by shyamvs1001** [comment]
I couldn't get google-map-poly(the one in demo) to work with angular 2(beta.0) either. Although it works perfectly independently. The points and the lines are not rendered. Just wanted to know if it is related. I tried this.distributeContent(true), but it didn't help.

**Comment by fr3dm4n** [comment]
Yes, I can confirm this.
I played around with it, also with the MutationObserver, but no luck :(

**Comment by robisim74** [comment]
Hi @fr3dm4n,

you should solve your problem (the first Plunker link) by adding the following code before importing the Polymer elements:
```
<script type="text/javascript">
     var Polymer = Polymer || {};
     Polymer.dom = 'shadow';
</script>
...
<link rel="import" href="https://cdn.rawgit.com/download/polymer-cdn/1.2.3.2/lib/google-map/google-map.html">
<link rel="import" href="https://cdn.rawgit.com/download/polymer-cdn/1.2.3.2/lib/google-map/google-map-marker.html">
```
See [here](https://www.polymer-project.org/1.0/docs/devguide/settings.html) and [this issue](https://github.com/angular/angular/issues/4670)

**Comment by fr3dm4n** [comment]
Indeed, it does fix the google-map problem. More interesting: I rebuild the whole app in Aurelia and everything works like it should...
I wonder what Angular 2 is doing here.
Thx for your response. I will close the ticket.
