### ISSUE TITLE
Doesn't render correctly if hidden during loading.

### ISSUE THREAD

**Issue by zmoshansky** [GoogleWebComponents/google-map#259]
I have an SPA with roughly the following structure:
* `neon-animated-pages`
  * `neon-animatable` web component
    * `paper-card`
      * `google-map`

If the google-map page is not selected while loading, it fails to render correctly.
![screenshot from 2016-02-15 16-34-03](https://cloud.githubusercontent.com/assets/3180807/13063906/fbe60b64-d401-11e5-9cae-d8fec65e91cc.png)

By sheer luck I resized the window discovering that it fixed the issue.
![screenshot from 2016-02-15 16-36-29](https://cloud.githubusercontent.com/assets/3180807/13063931/4ef13aa4-d402-11e5-81c7-cbf271a2d513.png)

### Possible Workarounds
(`active` is a property that is changed to true when the page is selected).

```
<template is="dom-if" if="[[active]]">
  <google-map latitude="{{_lat}}" longitude="{{_lng}}" fit-to-markers single-info-window>
  ...
```

or 
```
_activeChanged: function(active) {
  this.$$('google-map').resize();
}
```

**Comment by ebidel** [comment]
Related to https://github.com/GoogleWebComponents/google-map/issues/33#issuecomment-49125708, https://github.com/Polymer/core-animated-pages/issues/10, https://github.com/PolymerElements/iron-pages/issues/13, and others.

Both of those workarounds are the recommended approach when the map does not size itself properly at load time.
