### ISSUE TITLE
goolge-map-poly does not render inside a template

### ISSUE THREAD

**Issue by adampwells** [GoogleWebComponents/google-map#261]
I am trying to render a set of polygons, but the google-map-poly element does not seem to render inside a template.  I can use the template to loop over the points for a given polygon.

`        <google-map id="map" latitude="-27.39145277316188" longitude="153.0499843" apiKey="AIzaSyXXXXXXXXXXXXXXXXXXXXXXX" zoom="16" editable="true" class="flex">

          
          <template is="dom-repeat" items="polygons">
            <google-map-poly closed fill-color="red" fill-opacity=".05" stroke-weight="1" id="poly" editable="true">
              <template is="dom-repeat" items="{{item.points}}" as="p">
                <google-map-point latitude="{{p.lat}}" longitude="{{p.lon}}"></google-map-point>
              </template>
            </google-map-poly>
          </template>

          
          <google-map-poly closed fill-color="red" fill-opacity=".05" stroke-weight="1" editable="true">
            <template is="dom-repeat" items="{{polygon.points}}" as="p">
              <google-map-point latitude="{{p.lat}}" longitude="{{p.lon}}"></google-map-point>
            </template>
          </google-map-poly>

          
          <template is="dom-repeat" items="{{placemarks}}">
            <google-map-marker id="placemark-{{index}}" latitude="{{item.lat}}" longitude="{{item.lon}}" draggable="true" drag-events hidden="{{!item.checked}}"></google-map-marker>
          </template>

        </google-map>
`

**Comment by ebidel** [comment]
` items="polygons"` looks suspect

**Comment by adampwells** [comment]
my bad - sorry about that!
