### ISSUE TITLE
No Google Maps API Key or Client ID specified

### ISSUE THREAD

**Issue by jongmana** [GoogleWebComponents/google-map#269]
has something changed in the google-maps component?
When I now develop a minimal site with just the google-map component in it, without any attributes `<google-map></google-map>`, I'll get the message "No Google Maps API Key or Client ID specified" in my javascript console.

This is quite a show stopper when you want to do the google-maps code lab ( https://codelabs.developers.google.com/codelabs/polymer-maps/index.html?index=..%2F..%2Fpolymer-summit&viewga=UA-39334307-12 ) without the Chrome Dev Editor.

**Comment by ebidel** [comment]
Yes. We added a check because the maps api soon plans to require a key on
new apps.
