### ISSUE TITLE
Timing related crash when using api-key

### ISSUE THREAD

**Issue by rbjarnason** [GoogleWebComponents/google-map#271]
When use my api-key for this element, I get a crash when I first load a page using a google-map. If I navigate around paper-tabs that then use dom-if restamp to show and hide the map element, it works fine going forwards, the crash only happens when I first load the page.

Everything works fine when I don't use my api-key.  Our app is a Google Maps heavy citizens participation application that is being launched with the city of Reykjavik 22. April to 10's of thousands of users for a participatory budgeting event.  What are the consequences of not using the api-key?  Will my maps just stop working at some point.

Here is a screenshot of the crash along with the debugger info:
![mapswithapikeyerror](https://cloud.githubusercontent.com/assets/43699/14220039/26a95490-f84d-11e5-87c4-4ab3197edca3.png)

ps. Even when I do use my api-key I seem to get warnings from google maps that I'm not using apiKey or clientId, how can this be?

**Comment by ebidel** [comment]
How are you specifying the api key? It needs to be used as an attribute on all google maps * elements (e.g. api-key="123") so the library is loaded the same way for every component.

**Comment by rbjarnason** [comment]
Thanks @ebidel I tried hard coding my api-key references and then it works as expected. The problem with timings are on my side after all, in relations to making sure api-key is set dynamically before the elements are used.
