### ISSUE TITLE
Directions doesn't observe start-address and end-address

### ISSUE THREAD

**Issue by DavidHudlow** [GoogleWebComponents/google-map#278]
Because google-map-directions doesn't observe its address fields, binding on them doesn't really work. It really limits the usefulness for user-interaction.

**Comment by ebidel** [comment]
Hmm, it should. Any time startAddress/endAddress changes after the fact, `_route()` should be called: https://github.com/GoogleWebComponents/google-map/blob/master/google-map-directions.html#L146

**Comment by DavidHudlow** [comment]
You're right. My bad. It was only reading that way because I missed the automatic camelCase to delimiter-separated conversion between HTML elements and Polymer properties.
