### ISSUE TITLE
global-search is not ignored if radius is set

### ISSUE THREAD

**Issue by Nitin-Prabhakar** [GoogleWebComponents/google-map#300]
![google-map](https://cloud.githubusercontent.com/assets/15086525/15799075/2ec89f5c-2a6e-11e6-8b6e-017a77c42c4b.png)
The documentation states, that global-search is ignored if radius is set.

but this is what I see in the source code

```
if (!this.globalSearch) {
          var bounds = this.map.getBounds();
        } else if (this.radius) {
          var radius = this.radius;
          var location = this.location ? this.location : this.map.getCenter();
        }
```
shouldn't it be 
```
if (this.radius) {
                var radius = this.radius;
                var location = this.location ? this.location : this.map.getCenter();
            } else {
                if (!this.globalSearch) {
                    var bounds = this.map.getBounds();
                }
                else{
                  //do something if global search is true
                }
            }
```

**Comment by ebidel** [comment]
I think they achieve the same thing but yours is easier to read. If you're not doing a global search, restrict to the map bounds. of you are and radius is set, use the radius instead.

**Comment by Nitin-Prabhakar** [comment]
What happens, if, 
1 Radius isn't set
and
2 Global search is set?
I feel that use case isn't handled

**Comment by ebidel** [comment]
Haven't verified, but `bounds` will be `undefined` and I assume the API will search the entire world?
