### ISSUE TITLE
Make testing workflow more convenient

### ISSUE THREAD

**Issue by ukabu** [GoogleWebComponents/google-map#302]
Right now, we cannot do a clone of the repo, install dependencies and run tests.

Instead, we have to bower install google-map and then run tests from within the `bower_components` folder structure (see #81). This is really backward. 

I suggest that test cases use `../bower_components/[path]` instead of `../../[path]` in their script tags.

This would make contributing to this repo much more convenient.

**Comment by ebidel** [comment]
This is the recommended approach for https://github.com/Polymer/web-component-tester.

Running the tests in a repo checkout works for me:

    git clone git@github.com:GoogleWebComponents/google-map.git
    cd google-map;
    bower install
    wct -l chrome

**Comment by ukabu** [comment]
They do run from the command line.

However, they don't load when served using a [web server](https://github.com/Polymer/web-component-tester#web-server)(used `polymer serve`) and opened in the browser.

**Comment by ebidel** [comment]
I see. You may want to suggest this over on that repo.
