### ISSUE TITLE
Google Maps API error: MissingKeyMapError 

### ISSUE THREAD

**Issue by radiia** [GoogleWebComponents/google-map#309]
I use google-map element this, way, with a valid api key generated for my app, I also withelisted my urls (local / deployed)
`<google-map fit-to-markers="true" language="en" zoom="13" api-key="[[maps_key]]"></google-map>`

But I'm still getting this error (sometimes it works, but most of the time it fails)

**Comment by ebidel** [comment]
You'll have to post a jsbin that repos the issue.

**Comment by mlisook** [comment]
When you use a data bound api-key, the api call to load maps may be made before polymer applies the value (maps_key) to the api-key property. This happens intermittently _even if the key is given as a default value_. This can be seen in the dev tools network tab.

One of the projects I'm working on requires a data bound api-key also. To make it work I've had to wrap the google-map in a dom-if template:

```
<template is="dom-if" if="{{maps_key}}">
  <google-map id="ffmap" latitude="[[_latLng.lat]]" longitude="[[_latLng.lng]]"  api-key="[[maps_key]]">
  </google-map>
</template>

```

**Comment by Fausto-theXS** [comment]
I am trying @mlisook approach with a dom-if, however for some reason I am unable to isolate, when doing that the position for #map gets modified to relative, hiding the map (see below from the console)
Any idea on how to avoid that?

element.style {
    position: relative;
    overflow: hidden;
    background-color: rgb(229, 227, 223);
}
<style>…</style>
#map.google-map {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
}
