### ISSUE TITLE
Redundant code - google-map-search results already have latitude and longitude

### ISSUE THREAD

**Issue by Nitin-Prabhakar** [GoogleWebComponents/google-map#317]
The snippet below , doesn't serve any purpose as the search results already have latitude and longitude

![screenshot from 2016-08-12 16-59-11](https://cloud.githubusercontent.com/assets/15086525/17621167/27a2a7dc-60af-11e6-89b2-71abca47b41f.png)

``` Screenshot from console.log(result); ```

![screenshot from 2016-08-12 17-27-14](https://cloud.githubusercontent.com/assets/15086525/17621640/45dc9584-60b2-11e6-9db5-8a647537a6e9.png)

![screenshot from 2016-08-12 17-03-58](https://cloud.githubusercontent.com/assets/15086525/17621181/3543bc5a-60af-11e6-8275-d15fda356b21.png)

**Comment by ebidel** [comment]
Are you sure?  This is not true according to the docs (https://developers.google.com/places/web-service/search#PlaceSearchResponses). If you remove the two lines that set the properties on the `result` object, what does the console print?

**Comment by Nitin-Prabhakar** [comment]
Darn! That was a bad bad testing I did. We can ignore #318 
and close this as well. 

closing this
