### ISSUE TITLE
disableMapTypeControl doesn't appear to be working.

### ISSUE THREAD

**Issue by beowulf127** [GoogleWebComponents/google-map#324]
disableMapTypeControl doesn't appear to be working on Canary, Chrome, Firefox or Safari.  The only way I could get it to work temporarily was by setting the property to true in the google-map.html file.

**Comment by ebidel** [comment]
Can you check that https://github.com/GoogleWebComponents/google-map/blob/master/google-map.html fixes this for you?

**Comment by beowulf127** [comment]
Thanks!  Everything is working now.
