### ISSUE TITLE
google-map does not render to its size when used in core-animated-pages when it is in secion 1+

### ISSUE THREAD

**Issue by tobiashutterer** [GoogleWebComponents/google-map#33]
using <google-map> in a <core-animated-pages> just works right on index=0. When i try using or styling it on index 1-x the box is as i defined it, but the redered map just shows about 200px in the left upper corner of the map box.
. 
Might this me a bug, or am I too stupid? I hope it is the second one. 

![image](https://cloud.githubusercontent.com/assets/8007595/3585946/60e0286a-0c2b-11e4-8aa7-2c1f0516a959.png)

**Comment by phidias51** [comment]
I've noticed the same problem when embedding the map in a core-pages element or a core-collapse element.  It looks like the map is being translated up and to the left, leaving grey space behind in its wake.  The position is not centered in the middle of the map.  Also, the map.resize() call is causing the original lat/longs to be shifted.

**Comment by Zippersk** [comment]
I have same problem with neon-animated-pages. I can't find som fire like neon-animated-pages-transition-prepare. Is there any solution to display map?

**Comment by atotic** [comment]
Pull #152 should have fixed this for neon-animated-pages. Have you tried #master

**Comment by Zippersk** [comment]
Install master verison helps! Thaks a lot. :)

**Comment by kingflurkel** [comment]
I still have this bug with neon-animated-pages. 
I use this version:     "google-map": "GoogleWebComponents/google-map#^1.0.0",
Any help / tips to get this working?

**Comment by atotic** [comment]
@kingflurkel if you have a test case, I can take a look

**Comment by kingflurkel** [comment]
http://actaanbod.bitballoon.com/
Click on the location icon. So I have google-map within iron-animated-pages.
Code: 
https://github.com/A-StadLabs/activiteitenaanbod/tree/master/app/elements/a-activiteitenstage
https://github.com/A-StadLabs/activiteitenaanbod/blob/master/app/elements/a-locatie/a-locatie.html

**Comment by atotic** [comment]
Thanks.
google-map is not getting the iron-resize event. I'll have to dig in to
find out why.

**Comment by kingflurkel** [comment]
Maybe because google-map is in another custom-element, which is in iron-pages?

**Comment by atotic** [comment]
The problem is in the neon-animated-pages. Because map is inside a custom element, it does not get a notification that it has been shown.  Iniside neon-animated-pages:

```
      this.resizerShouldNotify = function(element) {
        return element == selectedPage;
      }
      this.notifyResize();
```

This should probably be: if element is selectedPage, or its parent is a selected page.

**Comment by atotic** [comment]
This issue was moved to PolymerElements/neon-animation#57
