### ISSUE TITLE
Wrong info window position when calling open(map, marker)

### ISSUE THREAD

**Issue by kroikie** [GoogleWebComponents/google-map#333]
If I call open(map, marker) on my google-map-marker the InfoWindow is displayed, however the InfoWindow is not offset above the marker like when the marker is clicked. Instead it seems to be anchored at the same position as the marker thus causing the InfoWindow to block the marker.

**Comment by ebidel** [comment]
Do you have a jsbin that repro's the issue?  Can you try setting `google-map-marker.open = true` instead and see if that works?

In the [demo](https://elements.polymer-project.org/elements/google-map?view=demo:demo/index.html&active=google-map), if I select the `<google-map-marker>` in the inspector and set it's `open` property to `true`, the info window opens in the correct location.

**Comment by kroikie** [comment]
Updating the property in the inspector does work, so I'll give `google-map-marker.open = true/false` a try. I'll close this issue and open another with a jsbin if it does not work.

Thanks!
