### ISSUE TITLE
google-map-poly-click event not firing

### ISSUE THREAD

**Issue by derappelt** [GoogleWebComponents/google-map#340]
google-map-poly-click events are not firing as expected.
I've created a JS Bin to demonstrate the problem. In there are one marker and one poly. 
The click event on the marker is working, the event on the poly is not.
[JS Bin](https://jsbin.com/keditunevo/1/edit?html,output)

Am I doing something wrong or is it broken?

**Comment by ebidel** [comment]
Not sure the jsbin saved correctly. Can you repost?
