### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by masonlouchart** [GoogleWebComponents/google-map#346]
There is not documentation for the [google-map-poly](https://github.com/GoogleWebComponents/google-map/blob/master/google-map-poly.html) and [google-map-point](https://github.com/GoogleWebComponents/google-map/blob/master/google-map-point.html) elements.

**Comment by nerdkid93** [comment]
I'm assuming your talking about external documentation, like the API and Demos on [WebComponents](https://www.webcomponents.org/element/GoogleWebComponents/google-map) for `google-map`, `google-map-directions`, `google-map-search`, and `google-map-marker`. There is documentation for both `google-map-poly` and `google-map-point` in their respective files, but it seems that it wasn't done correctly. Perhaps you should open a PR with the updated files so they better follow Polymer documentation procedures found [here](https://www.polymer-project.org/1.0/docs/tools/documentation).

**Comment by FluorescentHallucinogen** [comment]
See #391. :wink:

**Comment by e111077** [comment]
fixed in #392
