### ISSUE TITLE
google-map-marker is not shown

### ISSUE THREAD

**Issue by HugoMarteau** [GoogleWebComponents/google-map#352]
I'm displaying the map with google-map correctly but when I want to create a marker inside, it is simply not taken in consideration.
![image](https://cloud.githubusercontent.com/assets/8122998/22595771/2ff3764c-ea29-11e6-9797-f427ef8bf460.png)

![image](https://cloud.githubusercontent.com/assets/8122998/22595862/7e9c23ac-ea29-11e6-96f5-ee668c8781d7.png)

Even if I change the coordinates of the marker and add fit-to-marker to the google-map , the map is still showing me the default position (San fransisco) without the marker.

**Comment by HugoMarteau** [comment]
Update
I acheived to display the markers just adding 

  <script>
    window.Polymer = {
      dom: 'shadow'
    };
  </script>

in the head of index.html

**Comment by nerdkid93** [comment]
The attribute is also called `fit-to-markers`
