### ISSUE TITLE
Unable to style infoWindow content [2.0-preview]

### ISSUE THREAD

**Issue by Bodhiz** [GoogleWebComponents/google-map#372]
Hi there,

Trying 2.0-preview branch of the component, it seems impossible to style the content of info window except using inline style which is not very clean way to do it. 

Here is a JSBin demonstrating the issue : https://jsbin.com/qiboluq/edit?html,console,output

**Comment by mlisook** [comment]
This issue has always existed under Shadow DOM.  It's related to the way the info window is created by effectively moving elements of the info window markup from light dom to shadow dom.  If you look into issue 288 and the extensive discussion under PR 294, you'll have some idea of the nature of this issue and why it is unlikely to be fixed.
