### ISSUE TITLE
Listener doesn't work in infoWindow [2.0-preview]

### ISSUE THREAD

**Issue by Bodhiz** [GoogleWebComponents/google-map#373]
Hi there,

On 2.0 preview,  listener events in the slotted content of google-map-marker doesn't work. 
Here is a JSBin demonstrating this : https://jsbin.com/qiboluq/edit?html,console,output

**Comment by mlisook** [comment]
This has been the case since the first release.  See issue 288 and PR 294.  I don't believe this can be fixed using the native info window.
