### ISSUE TITLE
Place Autocomplete component/service

### ISSUE THREAD

**Issue by mbykovskyy** [GoogleWebComponents/google-map#42]
It would be nice to have a place autocomplete component which can be styled by a user or a service which can be bound to an input textfield.

**Comment by robertrafferty** [comment]
I would like to see the Google Places API in a webcomponent.

**Comment by ebidel** [comment]
Closing as this is pre Polymer 1.0. Please reopen if you can still reproduce or want to see this implemented in the new element.

**Comment by gorkamolero** [comment]
Yes please! Implement! Implement!

**Comment by kaskaderc** [comment]
+1 for making this happen, Can we reopen this FR please?

**Comment by ebidel** [comment]
I think this is a good idea but we're trying not that take on additional maintenance work for new elements. Does the community one not serve your needs?

**Comment by gorkamolero** [comment]
It seems like it's one of the few remaining details of the component. Sure, we could do without but it's always going to be way more muddy and convoluted.
