### ISSUE TITLE
Impossible to enter chars 'k' or 'm' in any input after dragging the map.. Weird bug.

### ISSUE THREAD

**Issue by yairopro** [GoogleWebComponents/google-map#420]
This is a really weird bug.
Here's [a jsFiddle to try it](https://jsfiddle.net/3n74jduc/).

**Instructions**
First drag a little the map.
Then try to write the char `k` or `m` in the input above. You won't be able to.

**Comment by bungambohlah** [comment]
i have a same issue for this

**Comment by bungambohlah** [comment]
maybe u can enable this property for solving this issue, if u don't use the controls
`disable-default-ui="true"`

i'v forked ur jsFiddle and u can see [this](https://jsfiddle.net/b5g3nudy/2/)

**Comment by bungambohlah** [comment]
Or u can set keyboardShortcuts to be false, and u can use default UI as ur controllers, but u can't use keybinding as controller, see this [jsFiddle](https://jsfiddle.net/7qawpzhh/1/)

**Comment by KeithHenry** [comment]
This is a bug in the underlying Maps API when in Shadow DOM: https://issuetracker.google.com/issues/73644075

The only workaround I've found is to disable keyboard `keyboardShortcuts: false` and re-implement them.

**Comment by KeithHenry** [comment]
Possible dupe of #415

**Comment by yairopro** [comment]
Yes it looks like
