### ISSUE TITLE
Panning the map across Pacific Ocean causes infinite loop

### ISSUE THREAD

**Issue by keanulee** [GoogleWebComponents/google-map#50]
Caused by #45 (issue does not exist with previous commit)

Panning the map fires 'center_changed' event, which updates `this.latitude` and `this.longitude` which are observed and calls `this.updateCenter()`, which pans to `this.latitude` and `this.longitude`, and so on.

**Comment by funkdified** [comment]
This also fixes this issue (from 2011) https://code.google.com/p/gmaps-api-issues/issues/detail?id=3247, which I ran into today using api v3
