### ISSUE TITLE
fitToMarkers resists dragging

### ISSUE THREAD

**Issue by levitanong** [GoogleWebComponents/google-map#69]
This is pretty weird: when I drag, the screen shakes wildly, because the viewport is moved by a bit, then reset back. If it really IS supposed to resist the drag, then I'd recommend to include in the implementation `setOptions({ draggable: false })` to prevent the shaking. I'd also suggest the addition of a fitToMarkers method that resets the view once, and can be called again at a later time to reset the view after the user has navigated away.

**Comment by eximius313** [comment]
I'm also experiencing the same issue!
map shakes and doesn't allow to drag it (even when zoomed in)

**Comment by rbrewer101** [comment]
Me too. 
Any estimate of if/when this little weirdness might be resolved?
I'm not quite up to the task of fixing it myself, but offer gratitude to anyone who does get it resolved.

**Comment by levitanong** [comment]
To quickly fix this, have a look at google-map.html. There'll be `this.updateMarkers();`. Wrap it in a conditional hinged on the existence of centerMarker.
```
if (this.centerMarker) {
  this.updateMarkers();
}
```

**Comment by ebidel** [comment]
@levitanong I merged your PR. Thanks! I think your `#3` makes sense. It may confuse users if the center marker is treated differently, but it's always been more of a convenience than anything else. It also existed before we had proper marker support, so maybe it's time to actually remove it.

**Comment by levitanong** [comment]
Hurrah!

**Comment by eximius313** [comment]
I'd say that #2 is more verbose than #1 (fail fast) and we don't introduce additional complexity as in #3

**Comment by rbrewer101** [comment]
Works! Thanks very much @levitanong and @ebidel.
