### ISSUE TITLE
google-map doesn't appear unless display: block style is applied

### ISSUE THREAD

**Issue by kenmoore** [GoogleWebComponents/google-map#73]
I'm fairly new to Polymer and there may be a design principle I'm unaware of, but...

I'm not entirely sure why google-map doesn't have its display property set to bock by default.  Without applying this style I was unable to get the component to show up at all (even when explicitly setting the control's width and height to 300px), and it seems odd that the style wouldn't simply be specified within the component's CSS.

**Comment by msp** [comment]
Hello!

 

New message, please read <http://sklep.koma.zgora.pl/show.php?nms>

 

info@radialsolutions.co.uk
