### ISSUE TITLE
Unable to load google heat map!

### ISSUE THREAD

**Issue by vinz** [GoogleWebComponents/google-map#79]
I have used the google maps element something like this :

```HTML
<google-map id="myMap" zoom="17" libraries="places,visualization" disableDefaultUI fitToMarkers>
</google-map>
```

and i followed the tutorial from here : https://developers.google.com/maps/documentation/javascript/examples/layer-heatmap

But i get this error 
![image](https://cloud.githubusercontent.com/assets/1381269/5330373/26d6b1ec-7e14-11e4-8585-009d0a20635d.png)

Without heatmap it works fine i.e., normal plotting of markers works fine.

Can you guys please fix this asap. We have a demo to one of our customers tomorrow evening and we need to heat maps for one of the use case. Atleast some workaround or temporary fix would be great.

Thanks a lot,
Vinay

**Comment by ebidel** [comment]
Closing as this is pre Polymer 1.0. Please reopen if you can still reproduce or want to see this implemented in the new element.
