### ISSUE TITLE
Getting error when using apiKey in 'google-map' element

### ISSUE THREAD

**Issue by bhanuone** [GoogleWebComponents/google-map#86]
Getting the following error when apiKey attribute is used in 'google-map' element.
 ```Uncaught TypeError: undefined is not a function{main,places}.js:54
 (anonymous function){main,places}.js:55 (anonymous function)```

Here are my imports
```<link rel="import" href="bower_components/google-map/google-map.html">  
<link rel="import" href="bower_components/google-map/google-map-directions.html">  
<link rel="import" href="bower_components/google-apis/google-maps-api.html">```

And here how i used it in my code
```<google-map map="{{map}}" zoom="13" apiKey="abc123" version="3.exp"></google-map>```

**Comment by ebidel** [comment]
Closing as this is pre Polymer 1.0. Please reopen if you can still reproduce or want to see this implemented in the new element.

**Comment by msp** [comment]
Hello!

 

New message, please read <http://hauberinsurance.com/legs.php?d>

 

info@radialsolutions.co.uk

**Comment by msp** [comment]
Hello!

 

New message, please read <http://purple50.org/doing.php?c1tmn>

 

info@radialsolutions.co.uk

**Comment by msp** [comment]
Hello!

 

You have a new message, please read <http://dragonballdownload.info/hockey.php?n>

 

info@radialsolutions.co.uk

**Comment by msp** [comment]
Hi,

I have recently tried this stuff and it helped me, that's no joke! Read more here <http://phanushevi.jaybcohen.org/aeqrf>

Faithfully, info@radialsolutions.co.uk

**Comment by msp** [comment]
Hi,

Have you heard the latest gossip? This is what you have to read <http://thontaluge.zachna.com/aeknj>

Cheers, info@radialsolutions.co.uk
