### ISSUE TITLE
Add support for marker events

### ISSUE THREAD

**Issue by HriBB** [GoogleWebComponents/google-map#89]
What is the best way to handle google-map-marker click (or any other) event?

I can customize google-map-marker.html easily.

    mapReady: function() {
        this.marker = new google.maps.Marker(...);
        this.contentChanged();
        setupDragHandler_.bind(this)();
        setupClickHandler_.bind(this)();
      },
    
    function setupClickHandler_() {
      this.clickHandler_ = google.maps.event.addListener(this.marker, 'click', function() {
        this.fire('marker-click');
      }.bind(this));
    }
    
Then I can do
    
    <google-map-marker
            on-marker-click="{{markerClick}}"
            title="{{loc.name}}"
            latitude="{{loc.lat}}"
            longitude="{{loc.lng}}"
            icon="/images/markers/{{loc.types[0].type}}.png">
    </google-map-marker>
    
But of course customizing google-map-marker.html is not an option. If I try to extend the marker I have a problem with google-map template having the wrong content selector.

    <content id="markers" select="google-map-marker"></content>
    
Please add/show a way to handle click and other events.

EDIT: so I ended up copy-pasting and editing both google-map and google-map-marker because I need some custom attributes on the marker and it was just easier than trying to extend them. It's ok for now, but please we need a way to easily extend map and markers.

Thanks and keep up the good work

**Comment by ebidel** [comment]
`google.maps.event.addListener(googleMarkerEl.marker, 'click', function(e) { })` should do it.

**Comment by ebidel** [comment]
Should be fixed in https://github.com/GoogleWebComponents/google-map/pull/102/files
