### ISSUE TITLE
empty map tag is not working

### ISSUE THREAD

**Issue by AlaaAttya** [GoogleWebComponents/google-map#90]
<google-map></google-map> itself does not work. it works fine when adding the fit attribute just like <google-map fit>. it think it may be set by default?!

**Comment by ebidel** [comment]
Code snippet? I believe https://github.com/GoogleWebComponents/google-map/commit/c21c852faf8d9dacc6a8ad5dc7e3b3040748e177 fixes what you're talking about but I can't be sure without seeing what you're trying to do.

**Comment by ebidel** [comment]
As noted, this was already fixed but we haven't done a release since. Thanks for the PR though.
