### ISSUE TITLE
Integrating laravel blade syntax with polymer

### ISSUE THREAD

**Issue by TickledPink** [GoogleWebComponents/google-map#92]
hi,
im currently having trouble with your data binding syntax with laravel (PHP Framework) blade syntax it both use the '{{ }}' syntax, do you have any alternative to change the syntax?

Thank You,

**Comment by ebidel** [comment]
Unfortunately that's polymer's binding syntax. You should see if your
framework supports a "raw" template construct for telling the engine not to
process the block of markup.

**Comment by Shance** [comment]
If it's not possible to change Polymer's binding syntax, you still can change Blade's tags by doing this:
```php
Blade::setContentTags('<%', '%>');        // for variables and all things Blade
Blade::setEscapedContentTags('<%%', '%%>');   // for escaped data
```
Also you can include Polymer file inside Blade 
```php
@include('polymer-stuff'); <!-- app/views/polymer-stuff.php -->
```

> via [scotch.io](https://scotch.io/quick-tips/quick-tip-using-laravel-blade-with-angularjs)

**Comment by treed593** [comment]
@Shance great suggestion, worked like a dream!

**Comment by infacq** [comment]
what a relief, for `{{ var }}` to `@{{ var }}`. As simple as that
