### ISSUE TITLE
google-map-search v0.4.0 google-map-search-result firing with undefined result var

### ISSUE THREAD

**Issue by pdelanauze** [GoogleWebComponents/google-map#94]
https://github.com/GoogleWebComponents/google-map/blob/0.4.0/google-map-search.html#L90

I can see this is fixed in master , probably worth a cherry-pick & tag v0.4.1  ?

https://github.com/GoogleWebComponents/google-map/commit/5438a6ee325ed9c8399e94b2cb1442eafc3ae5da

**Comment by ebidel** [comment]
We're overdo for a release. I'll cut one.

**Comment by ebidel** [comment]
0.4.1 was released
